apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-web.fullname" . }}-content
  labels:
    {{- include "demo-web.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.content | indent 4 }}
